services:
  backend:
    build:
      context: ./backend
    container_name: kanban_backend
    command: uv run python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
      - /app/.venv
    ports:
      - "8000:8000"
    env_file:
      - .env

  frontend:
    build:
      context: ./frontend
      target: development
    container_name: kanban_frontend
    command: bun run dev --host 0.0.0.0
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - backend