# Generated by Django 6.0.4 on 2026-05-28 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pb', '0005_column_kind_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='status',
        ),
        migrations.AlterField(
            model_name='column',
            name='kind',
            field=models.CharField(choices=[('board', 'Board'), ('backlog', 'Backlog'), ('archive', 'Archive')], default='board', max_length=20),
        ),
    ]
