# Generated by Django 6.0.4 on 2026-06-04 03:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pb', '0007_taskcomment_taskcommentreadstate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='added_to_board_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('task_created', 'Task Created'), ('task_moved', 'Task Moved'), ('task_archived', 'Task Archived'), ('task_restored', 'Task Restored'), ('task_assigned', 'Task Assigned'), ('task_unassigned', 'Task Unassigned'), ('task_deadline_set', 'Task Deadline Set'), ('column_created', 'Column Created'), ('column_moved', 'Column Moved'), ('column_archived', 'Column Archived'), ('column_cleared', 'Column Cleared'), ('member_joined', 'Member Joined'), ('member_left', 'Member Left')], max_length=30)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='pb.board')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['board', 'created_at'], name='pb_activity_board_i_708de9_idx'), models.Index(fields=['board', 'action_type'], name='pb_activity_board_i_b9fc6c_idx')],
            },
        ),
    ]
