# Generated by Django 6.0.4 on 2026-06-17 13:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pb', '0008_task_added_to_board_at_activitylog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action_type',
            field=models.CharField(choices=[('task_created', 'Task Created'), ('task_moved', 'Task Moved'), ('task_archived', 'Task Archived'), ('task_restored', 'Task Restored'), ('task_assigned', 'Task Assigned'), ('task_unassigned', 'Task Unassigned'), ('task_deadline_set', 'Task Deadline Set'), ('column_created', 'Column Created'), ('column_moved', 'Column Moved'), ('column_archived', 'Column Archived'), ('column_cleared', 'Column Cleared'), ('member_joined', 'Member Joined'), ('member_left', 'Member Left'), ('mentor_request_created', 'Mentor Request Created'), ('mentor_request_started', 'Mentor Request Started'), ('mentor_request_resolved', 'Mentor Request Resolved'), ('mentor_request_cancelled', 'Mentor Request Cancelled')], max_length=30),
        ),
        migrations.CreateModel(
            name='TaskMentorRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_type', models.CharField(choices=[('help', 'Help'), ('review', 'Review')], max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('message', models.TextField()),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('close_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_mentor_requests', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_mentor_requests', to=settings.AUTH_USER_MODEL)),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='started_mentor_requests', to=settings.AUTH_USER_MODEL)),
                ('started_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='started_mentor_requests', to='pb.taskcomment')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_requests', to='pb.task')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['open', 'in_progress'])), fields=('task',), name='unique_active_mentor_request_per_task')],
            },
        ),
    ]
